%YAML:1.0

image_height: 480
image_width: 848
use_imu: 1

depth_lower_thr: 0.1
depth_upper_thr: 10.0
max_y_diff: 2

# Calibration
distortion_type: 0  # 0 for undistorted inputs, 1 for radial-tangential: [k1, k2, p1, p2, k3], 2 for equidistant/fisheye:  [k1, k2, k3, k4, 0].
cam0:
  intrinsics: [426.1531982421875, 426.1531982421875, 423.66717529296875, 240.55062866210938] # fx, fy, cx, cy
  distortion_coeffs: [0.0, 0.0, 0.0, 0.0, 0]
  T_type: 0           # 0 for Euroc format, the following T is Tbc. 1 for Kalibr format, the following T is Tcb
  T: 
  - [1.0, 0.0, 0.0, 0.0]
  - [0.0, 1.0, 0.0, 0.0]
  - [0.0, 0.0, 1.0, 0.0]
  - [0.0, 0.0, 0.0, 1.0]
cam1:
  intrinsics: [426.1531982421875, 426.1531982421875, 423.66717529296875, 240.55062866210938] # fx, fy, cx, cy
  distortion_coeffs: [0.0, 0.0, 0.0, 0.0, 0]
  T_type: 0           
  T: 
  - [1.0, 0.0, 0.0, 0.05]
  - [0.0, 1.0, 0.0, 0.0]
  - [0.0, 0.0, 1.0, 0.0]
  - [0.0, 0.0, 0.0, 1.0]

# IMU parameters (required when use_imu: 1)
rate_hz: 200.0
gyroscope_noise_density: 0.00016968
gyroscope_random_walk: 0.000019393
accelerometer_noise_density: 0.002
accelerometer_random_walk: 0.003
g_value: 9.81007
